chore: add templates and base files
The-Mycelium-Network/project-template pull request #2
Opened 2022-10-23 20:52 UTC by schalkneethling

Initial commit of project template files.

fix #1

2022-10-24 23:00 UTC, bpires commented on README.md
>  # project-template
```suggestion
# The Mycelium Network Project Template Repository
```

2022-10-24 23:04 UTC, bpires commented on README.md
> +A project template repository based on the [template repository](https://github.com/cncf/project-template) by the [Cloud Native Computing Foundation](https://github.com/cncf).
```suggestion

This is a [template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) for our community projects. It can be used either to start a new project or just to grab particular files.

This project template repository is based on the [template repository](https://github.com/cncf/project-template) by the [Cloud Native Computing Foundation](https://github.com/cncf).

## Instructions

Creating a repository from a template is a great way to start a new project quickly. You just have to click on the `Use this template` button above the file list, and then follow the given instructions. With the repo created, customize every template and address each TODO item.
```

I thought more information on the purpose of the repository was needed, as well as some instructions on how to use it.

2022-10-24 23:05 UTC, bpires commented on README.md
> +This project is licensed under [Apache license 2.0](LICENSE).
Why shift from MIT License to Apache License?

2022-10-24 23:18 UTC, bpires commented
This is a great initiative! It'll take some time for me to go through all the files and leave my review. Just added some comments for now and will revisit this shortly.

2022-11-20 17:36 UTC, bpires requested changes
Great read! Establishing these guidelines is key to knowing where to move forward. I reckon this is well validated in the open-source community, but, with time, we can make improvements and adapt to the Mycelium Network's needs. I'm also thinking that making a more beginner-friendly/succinct or visual version of it could be beneficial (but that's sth to get back in the future).

@schalkneethling, ,most of the reviews were just typos or punctuation on lists (for consistency), but, about the License, I think we should stick with the MIT we are already using. I believe it is more common and people are more familiar with it. Also, for projects that have a huge load of written content, more than code, we should consider adding a [Creative Commons license](https://creativecommons.org/) as our standard choice for non-software content.

> _(...) Mixed projects_
> _If your project contains a mix of different types of material, you can include multiple licenses, as long as you are explicit about which license applies to each part of the project. See [the license notice for this site](https://github.com/github/choosealicense.com#license) as an example._
>
> Excerpt from [choosealicense.com/non-software](https://choosealicense.com/non-software/) by GitHub.

I've also updated the contributor covenant for the [most recent version](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)!

2022-11-20 17:41 UTC, bpires commented on CODE_OF_CONDUCT.md
> +https://www.contributor-covenant.org/translations.
```suggestion
# Contributor Covenant Code of Conduct

## Our Pledge

We as members, contributors, and leaders pledge to make participation in our
community a harassment-free experience for everyone, regardless of age, body
size, visible or invisible disability, ethnicity, sex characteristics, gender
identity and expression, level of experience, education, socio-economic status,
nationality, personal appearance, race, caste, color, religion, or sexual
identity and orientation.

We pledge to act and interact in ways that contribute to an open, welcoming,
diverse, inclusive, and healthy community.

## Our Standards

Examples of behavior that contributes to a positive environment for our
community include:

* Demonstrating empathy and kindness toward other people
* Being respectful of differing opinions, viewpoints, and experiences
* Giving and gracefully accepting constructive feedback
* Accepting responsibility and apologizing to those affected by our mistakes,
  and learning from the experience
* Focusing on what is best not just for us as individuals, but for the overall
  community

Examples of unacceptable behavior include:

* The use of sexualized language or imagery, and sexual attention or advances of
  any kind
* Trolling, insulting or derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others' private information, such as a physical or email address,
  without their explicit permission
* Other conduct which could reasonably be considered inappropriate in a
  professional setting

## Enforcement Responsibilities

Community leaders are responsible for clarifying and enforcing our standards of
acceptable behavior and will take appropriate and fair corrective action in
response to any behavior that they deem inappropriate, threatening, offensive,
or harmful.

Community leaders have the right and responsibility to remove, edit, or reject
comments, commits, code, wiki edits, issues, and other contributions that are
not aligned to this Code of Conduct, and will communicate reasons for moderation
decisions when appropriate.

## Scope

This Code of Conduct applies within all community spaces, and also applies when
an individual is officially representing the community in public spaces.
Examples of representing our community include using an official e-mail address,
posting via an official social media account, or acting as an appointed
representative at an online or offline event.

## Enforcement

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported to the community leaders responsible for enforcement at
community (at) mechanical-ink (.co.za).
All complaints will be reviewed and investigated promptly and fairly.

All community leaders are obligated to respect the privacy and security of the
reporter of any incident.

## Enforcement Guidelines

Community leaders will follow these Community Impact Guidelines in determining
the consequences for any action they deem in violation of this Code of Conduct:

### 1. Correction

**Community Impact**: Use of inappropriate language or other behavior deemed
unprofessional or unwelcome in the community.

**Consequence**: A private, written warning from community leaders, providing
clarity around the nature of the violation and an explanation of why the
behavior was inappropriate. A public apology may be requested.

### 2. Warning

**Community Impact**: A violation through a single incident or series of
actions.

**Consequence**: A warning with consequences for continued behavior. No
interaction with the people involved, including unsolicited interaction with
those enforcing the Code of Conduct, for a specified period of time. This
includes avoiding interactions in community spaces as well as external channels
like social media. Violating these terms may lead to a temporary or permanent
ban.

### 3. Temporary Ban

**Community Impact**: A serious violation of community standards, including
sustained inappropriate behavior.

**Consequence**: A temporary ban from any sort of interaction or public
communication with the community for a specified period of time. No public or
private interaction with the people involved, including unsolicited interaction
with those enforcing the Code of Conduct, is allowed during this period.
Violating these terms may lead to a permanent ban.

### 4. Permanent Ban

**Community Impact**: Demonstrating a pattern of violation of community
standards, including sustained inappropriate behavior, harassment of an
individual, or aggression toward or disparagement of classes of individuals.

**Consequence**: A permanent ban from any sort of public interaction within the
community.

## Attribution

This Code of Conduct is adapted from the [Contributor Covenant][homepage],
version 2.1, available at
[https://www.contributor-covenant.org/version/2/1/code_of_conduct.html][v2.1].

Community Impact Guidelines were inspired by
[Mozilla's code of conduct enforcement ladder][Mozilla CoC].

For answers to common questions about this code of conduct, see the FAQ at
[https://www.contributor-covenant.org/faq][FAQ]. Translations are available at
[https://www.contributor-covenant.org/translations][translations].

[homepage]: https://www.contributor-covenant.org
[v2.1]: https://www.contributor-covenant.org/version/2/1/code_of_conduct.html
[Mozilla CoC]: https://github.com/mozilla/diversity
[FAQ]: https://www.contributor-covenant.org/faq
[translations]: https://www.contributor-covenant.org/translations

```

I'm updating the Contributor Covenant to their version 2.1.

I've kept the contacts as `community (at) mechanical-ink (.co.za)` address, but I didn't get why you haven't used `community@mechanical-ink.co.za`? (Also, isn't your domain `mechanical.ink`?)

2022-11-24 13:53 UTC, schalkneethling commented on README.md
> +This project is licensed under [Apache license 2.0](LICENSE).
The Apache is just for this repository because the CNCF repo this information comes from is licensed under the Apache License.

2022-11-24 13:59 UTC, schalkneethling commented on CODE_OF_CONDUCT.md
> +https://www.contributor-covenant.org/translations.
I own both :) The main reason for the weird syntax is to avoid bots.

2022-11-24 15:02 UTC, schalkneethling commented
@bpires First of all, thank you so much for your detailed review.  As mentioned, this repo is using the Apache license because of the origin of most of the content. I propose that we have a LICENSES file that mentions that there is a distinction between content created by the Mycelium Network and the origin of most of the resources.

We can then change the LICENSE file to MIT. In the README, we can then mention this and indicate that the LICENSES file should be deleted on repositories created from the template.

Regarding CC0 for written content, I 100% agree. This is what we do on MDN Web Docs as well. Let me know what you think.

2022-11-25 00:47 UTC, bpires commented on README.md
> +This project is licensed under [Apache license 2.0](LICENSE).
Ah, now I understand! It's the repository license and not the template license haha gotcha!

2022-12-04 22:05 UTC, schalkneethling commented
@bpires I have made several updates. As you would have seen, I moved some to [the Mycelium Network repository](https://github.com/The-Mycelium-Network/the-mycelium-network/pull/3) as I feel it fits better there. We can link to it where appropriate.

I still need to pare down the `CONTRIBUTING` doc in this repository.

2022-12-04 23:08 UTC, schalkneethling commented
@bpires Alrighty, this one and https://github.com/The-Mycelium-Network/the-mycelium-network/pull/3 is ready for review. Thanks!

2023-04-02 19:04 UTC, merged